name: venv-mpc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.10.16=0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py36_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.5.0
    - astor==0.7.1
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - backcall==0.1.0
    - bleach==3.0.0
    - certifi==2018.8.24
    - chardet==3.0.4
    - cloudpickle==0.5.6
    - commentjson==0.7.1
    - contextlib2==0.5.5
    - cycler==0.10.0
    - cython==0.29.5
    - dask==0.19.2
    - decorator==4.3.0
    - defusedxml==0.5.0
    - dotmap==1.2.39
    - entrypoints==0.2.3
    - future==0.16.0
    - gast==0.2.0
    - grpcio==1.15.0
    - h5py==2.9.0
    - idna==2.7
    - imageio==2.6.1
    - imgaug==0.2.7
    - ipykernel==5.0.0
    - ipython==7.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.1
    - jinja2==2.10
    - joblib==0.13.2
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - markdown==3.0.1
    - markupsafe==1.0
    - matplotlib==3.0.0
    - mistune==0.8.3
    - more-itertools==4.3.0
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - networkx==2.2
    - notebook==5.7.0
    - numpy==1.14.5
    - opencv-python==3.4.3.18
    - pandocfilters==1.4.2
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.3.0
    - pluggy==0.7.1
    - prometheus-client==0.4.0
    - prompt-toolkit==2.0.5
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - py==1.6.0
    - pyassimp==4.1.3
    - pyglet==1.3.2
    - pygments==2.2.0
    - pyopengl==3.1.0
    - pyopengl-accelerate==3.1.0
    - pyparsing==2.2.2
    - pytest==3.8.2
    - python-dateutil==2.7.3
    - python-qt-binding==0.3.4
    - pywavelets==1.0.1
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - requests==2.19.1
    - scikit-fmm==2019.1.30
    - scikit-image==0.14.1
    - scipy==1.3.1
    - send2trash==1.5.0
    - setuptools==39.1.0
    - shapely==1.6.4.post2
    - simplegeneric==0.8.1
    - six==1.12.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - toolz==0.9.0
    - tornado==5.1.1
    - traitlets==4.3.2
    - urllib3==1.23
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - widgetsnbextension==3.4.2
    - yattag==1.10.0
